# Generated by Django 5.0.6 on 2024-05-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P4', models.IntegerField(verbose_name='Indique la cantidad total de personal especializado de mano de obra de producción en un trimestre (en cantidad)')),
                ('P5', models.IntegerField(verbose_name='El total de personal especializado como máximo puede producir un total de unidades de productos terminados en trimestre de: (en cantidad)')),
                ('P6', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solo un personal especializado de mano de obra de producción en promedio tiene un costo trimestral de bolivianos. (Una sola persona)')),
                ('P8', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál es el precio de Materia Prima incluye: materia prima e insumos de fabricación?  (Bs. por unidad)')),
                ('P9', models.IntegerField(verbose_name='¿Cuántas unidades comprará de Materia Prima (materia prima e insumos)  para este trimestre (en cantidad)')),
                ('P10', models.IntegerField(verbose_name='¿Cuál es su capacidad máxima de producción unidades en un trimestre?  (en cantidad)')),
                ('P11', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de cada máquina')),
                ('P12', models.IntegerField(verbose_name='¿Cuál es el número de máquinas que comprará para este trimestre?')),
                ('P13', models.IntegerField(verbose_name='Cada máquina comprada ¿Cuántas unidades produce en promedio?')),
                ('P15', models.IntegerField(verbose_name='¿Qué cantidad de personal especializado contratará para este trimestre (en cantidad)')),
                ('P16', models.IntegerField(verbose_name='¿Qué cantidad de personal especializado despedirá para este trimestre (en cantidad)')),
                ('P17', models.IntegerField(verbose_name='Cantidad P17')),
                ('P18', models.IntegerField(verbose_name='Cantidad P18')),
                ('P19', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P19')),
                ('P22', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P22')),
                ('P23', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P23')),
                ('P24', models.IntegerField(verbose_name='Cantidad P24')),
                ('P25', models.IntegerField(verbose_name='Cantidad P25')),
                ('P26', models.IntegerField(verbose_name='Cantidad P26')),
                ('P27', models.IntegerField(verbose_name='Cantidad P27')),
                ('P28', models.IntegerField(verbose_name='Cantidad P28')),
                ('P29', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P29')),
                ('P30', models.IntegerField(verbose_name='Cantidad P30')),
                ('P31', models.IntegerField(verbose_name='Cantidad P31')),
                ('P33', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P33')),
                ('P34', models.IntegerField(verbose_name='Años P34')),
                ('P35', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% P35')),
                ('P36', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P36')),
                ('P37', models.IntegerField(verbose_name='Años P37')),
                ('P38', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% P38')),
                ('P40', models.CharField(max_length=100, verbose_name='Unidad P40')),
                ('P41', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P41')),
                ('P42', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bolivianos P42')),
                ('P43', models.CharField(max_length=100, verbose_name='Unidades P43')),
                ('P45', models.CharField(max_length=100, verbose_name='Unidades P45')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisiones.grupo')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
