# Generated by Django 5.0.4 on 2024-05-28 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['año', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='decisiones.semestre')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['semestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P4', models.IntegerField(verbose_name='Indique la cantidad total de personal especializado de mano de obra de producción en un trimestre (en cantidad)')),
                ('P5', models.IntegerField(verbose_name='El total de personal especializado como máximo puede producir un total de unidades de productos terminados en trimestre de: (en cantidad)')),
                ('P6', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solo un personal especializado de mano de obra de producción en promedio tiene un costo trimestral de bolivianos. (Una sola persona)')),
                ('P8', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál es el precio de Materia Prima incluye: materia prima e insumos de fabricación?  (Bs. por unidad)')),
                ('P9', models.IntegerField(verbose_name='¿Cuántas unidades comprará de Materia Prima (materia prima e insumos)  para este trimestre (en cantidad)')),
                ('P10', models.IntegerField(verbose_name='¿Cuál es su capacidad máxima de producción unidades en un trimestre?  (en cantidad)')),
                ('P11', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de cada máquina')),
                ('P12', models.IntegerField(verbose_name='¿Cuál es el número de máquinas que comprará para este trimestre?')),
                ('P13', models.IntegerField(verbose_name='Cada máquina comprada ¿Cuántas unidades produce en promedio?')),
                ('P15', models.IntegerField(verbose_name='¿Qué cantidad de personal especializado contratará para este trimestre (en cantidad)')),
                ('P16', models.IntegerField(verbose_name='¿Qué cantidad de personal especializado despedirá para este trimestre (en cantidad)')),
                ('P17', models.IntegerField(verbose_name='¿Qué cantidad de Personal administrativo contratará para este trimestre?  (en cantidad)')),
                ('P18', models.IntegerField(verbose_name='¿Qué cantidad de Personal administrativo despedirá para este trimestre? (en cantidad)')),
                ('P19', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Para solo un personal administrativo ¿Cuál es el costo en promedio por trimestre en bolivianos?. (Una sola persona)')),
                ('P22', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál será su Precio de Venta con factura? (Bs. por unidad)')),
                ('P23', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál será su Precio de Venta con factura a distribuidores? (Bs. por unidad)')),
                ('P24', models.IntegerField(verbose_name='¿Qué cantidad de Distribuidores contratará en este trimestre? (en cantidad)')),
                ('P25', models.IntegerField(verbose_name='¿Qué cantidad de Distribuidores despedirá en este trimestre? (en cantidad)')),
                ('P26', models.IntegerField(verbose_name='Publicidad Alcance: ¿Cuál es la cantidad de personas que alcanzará para este trimestre con su publicidad?')),
                ('P27', models.IntegerField(verbose_name='Publicidad frecuencia: ¿Cuál es la cantidad de salidas para este trimestre? (cantidad de veces por trimestre)')),
                ('P28', models.IntegerField(verbose_name='Indique el tiempo o la cantidad de minutos destinado por cada salida para un trimestre (introducir cuantos minutos son por una salida/trimestre)')),
                ('P29', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál es el precio en bolivianos por cada minuto de publicidad?')),
                ('P30', models.IntegerField(verbose_name='Cantidad de unidades a vender de su pronóstico en ventas para este trimestre')),
                ('P31', models.IntegerField(verbose_name='Cantidad de unidades a vender de su pronóstico en ventas para el próximo trimestre')),
                ('P33', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solicitud de monto de crédito operativo en bolivianos al Banco  (Monto en bolivianos)')),
                ('P34', models.IntegerField(verbose_name='Tiempo de crédito operativo en bolivianos al Banco  (años)')),
                ('P35', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de crédito operativo en bolivianos al Banco  (años)')),
                ('P36', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solicitud de monto de crédito de inversión en bolivianos al Banco  (Monto en bolivianos)')),
                ('P37', models.IntegerField(verbose_name='Tiempo de crédito de inversión en bolivianos al Banco  (años)')),
                ('P38', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de crédito de inversión en bolivianos al Banco  (años)')),
                ('P40', models.CharField(max_length=100, verbose_name='Innovación: Una unidad de materia prima equivale a una unidad de producto terminado para el primer trimestre 1-2024')),
                ('P41', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Para ampliar el tamaño de infraestructura actual (su casa propia) que cubra un espacio igual al de su capacidad de producción actual tiene un costo de')),
                ('P42', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='El alquiler mensual que le cobran sus padres por usar su infraestructura a partir del 2do trimestre 2024 es de ')),
                ('P43', models.CharField(max_length=100, verbose_name='Cantidad de unidades a producir')),
                ('P45', models.CharField(max_length=100, verbose_name='Cantidad de unidades a vender en este trimestre')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='decisiones.grupo')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='decisiones.grupo')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
