# Generated by Django 4.1.2 on 2024-05-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='P17',
            field=models.IntegerField(verbose_name='¿Qué cantidad de Personal administrativo contratará para este trimestre?  (en cantidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P18',
            field=models.IntegerField(verbose_name='¿Qué cantidad de Personal administrativo despedirá para este trimestre? (en cantidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P19',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Para solo un personal administrativo ¿Cuál es el costo en promedio por trimestre en bolivianos?. (Una sola persona)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P22',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál será su Precio de Venta con factura? (Bs. por unidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P23',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál será su Precio de Venta con factura a distribuidores? (Bs. por unidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P24',
            field=models.IntegerField(verbose_name='¿Qué cantidad de Distribuidores contratará en este trimestre? (en cantidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P25',
            field=models.IntegerField(verbose_name='¿Qué cantidad de Distribuidores despedirá en este trimestre? (en cantidad)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P26',
            field=models.IntegerField(verbose_name='Publicidad Alcance: ¿Cuál es la cantidad de personas que alcanzará para este trimestre con su publicidad?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P27',
            field=models.IntegerField(verbose_name='Publicidad frecuencia: ¿Cuál es la cantidad de salidas para este trimestre? (cantidad de veces por trimestre)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P28',
            field=models.IntegerField(verbose_name='Indique el tiempo o la cantidad de minutos destinado por cada salida para un trimestre (introducir cuantos minutos son por una salida/trimestre)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P29',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='¿Cuál es el precio en bolivianos por cada minuto de publicidad?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P30',
            field=models.IntegerField(verbose_name='Cantidad de unidades a vender de su pronóstico en ventas para este trimestre'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P31',
            field=models.IntegerField(verbose_name='Cantidad de unidades a vender de su pronóstico en ventas para el próximo trimestre'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P33',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solicitud de monto de crédito operativo en bolivianos al Banco  (Monto en bolivianos)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P34',
            field=models.IntegerField(verbose_name='Tiempo de crédito operativo en bolivianos al Banco  (años)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P35',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de crédito operativo en bolivianos al Banco  (años)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P36',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solicitud de monto de crédito de inversión en bolivianos al Banco  (Monto en bolivianos)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P37',
            field=models.IntegerField(verbose_name='Tiempo de crédito de inversión en bolivianos al Banco  (años)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P38',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de crédito de inversión en bolivianos al Banco  (años)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P40',
            field=models.CharField(max_length=100, verbose_name='Innovación: Una unidad de materia prima equivale a una unidad de producto terminado para el primer trimestre 1-2024'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P41',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Para ampliar el tamaño de infraestructura actual (su casa propia) que cubra un espacio igual al de su capacidad de producción actual tiene un costo de'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P42',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='El alquiler mensual que le cobran sus padres por usar su infraestructura a partir del 2do trimestre 2024 es de '),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P43',
            field=models.CharField(max_length=100, verbose_name='Cantidad de unidades a producir'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='P45',
            field=models.CharField(max_length=100, verbose_name='Cantidad de unidades a vender en este trimestre'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='decisiones.grupo'),
        ),
    ]
